# Generated by Django 6.0.1 on 2026-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('cover_url', models.TextField()),
                ('artist_id', models.IntegerField(blank=True, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
